GET http://localhost:5000/feed/post
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2MDA1MDc4ODYsImV4cCI6MTYwMDUwNzkwMSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdCJ9.h-Uh3SJfiZkSZAmoa85AyHzovgapQfGF8yVrMS_5R8U


### login
POST  http://localhost:3000/login
Content-Type: application/json

{
    "email" : "gaurav@gmail.com",
    "password" : "123456789"
}

### create User
POST  http://localhost:3000/user/create
Content-Type: application/json

{
    "name" : "",
    "email" : "gaura1v@mail.com",
    "password" : "",
    "user_type": "admin"
}
